name: Production Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      deployment: ${{ steps.path-filter.outputs.deployment }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          filters: |
            deployment:
              - "deployment/**"
              - ".github/workflows/prd-deploy.yaml"
  tf-apply:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.deployment == 'true'
    steps:
      - uses: actions/checkout@v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::891377239454:role/rssplus-github-actions-main
          role-session-name: GitHubActions
      - name: Terraform Init
        run: cd deployment/ && terraform init
        shell: bash
      - name: Terraform Apply
        run: cd deployment/ && terraform apply -auto-approve
        id: tf-apply
        shell: bash

  prd-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set now time to env
        id: set-now
        run: |
          NOW=$(date +'%Y%m%d%H%M%S')
          echo "now=$NOW" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: '.'
          file: ./Dockerfile
          tags: |
            ghcr.io/okabelab/rssplus:main-${{ github.sha }}-${{ steps.set-now.outputs.now }}
            ghcr.io/okabelab/rssplus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
